/***** DO NOT EDIT THIS FILE *****/
// demo.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var demo = {};

/*** script -- login ***/
demo.login = function(app) {
	MT.Script.call(this, app, "login.mt");
};

demo.login.prototype = new MT.Script;

demo.login.prototype.call = function(username, pwd) {
	//run: login.mt
	MT.Script.prototype.call(this, username, pwd);
};

MT.Application.prototype.login = function() {
	return new demo.login(this);
};

